package jankowiak.kamil.exceptions;

public enum ExceptionCode {
    INVALID_NAME, INVALID_PRICE, NAME_EMPTY, PRICE_EMPTY, INVALID_AGE, INVALID_EMAIL,
    CUSTOMER_EMPTY, PRODUCT_EMPTY, INVALID_QUANTITY, INVALID_DATE, PRODUCT_JSON_ERROR, GSON_ERROR, INVALID_NUMBER, INVALID_CATEGORY
}
